### ISSUE TITLE
Graphical Overview

### ISSUE THREAD

**Issue by rdmueller** [GeertBellekens/Enterprise-Architect-Shapescript-Library#1]
Is there somewhere a graphical overview of all symbols?

**Comment by thomaskilian** [comment]
This is not that easy. It would involve creating stereotyped elements/connectors and making screenshots. Both almost only possible manually (except you put in a lot of effort). Feel free to provide that ;-)

**Comment by rdmueller** [comment]
OK. So I think this issue should be closed :-)
